spring:
  application:
    name: english-api
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE:disable}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
#        id:
#          new_generator_mappings: true
#        jdbc:
#          batch_size: 60
#          order_inserts: true
#          order_updates: true
#        format_sql: true
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  jackson:
#    deserialization:
#      fail-on-unknown-properties: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration:
    access-token: ${JWT_ACCESSTOKEN_EXP} #s
    refresh-token: ${JWT_REFRESHTOKEN_EXP} #s
server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    url: /v3/api-docs

client:
  url:${CLIENT_URL}

